Repository Alt-Org/Altzone-WebPages, pull requests merged in 2024-11, with the labels that each got.

#253 Leo/refactor/auth forms
  frontend-next-migration/src/app/[lng]/(helper)/auth/layout.tsx
  frontend-next-migration/src/app/[lng]/(helper)/auth/login/page.tsx
  frontend-next-migration/src/app/[lng]/(helper)/auth/page.ts
  frontend-next-migration/src/app/[lng]/(helper)/auth/register/page.tsx
  frontend-next-migration/src/entities/Auth/index.ts
  frontend-next-migration/src/entities/Auth/ui/BaseAuthForm/BaseAuthForm.module.scss
  frontend-next-migration/src/entities/Auth/ui/BaseAuthForm/BaseAuthForm.tsx
  frontend-next-migration/src/features/AuthByUsername/index.ts
  frontend-next-migration/src/features/AuthByUsername/model/useLoginForm.ts
  frontend-next-migration/src/features/AuthByUsername/ui/LoginForm/LoginForm.async.tsx
  frontend-next-migration/src/features/AuthByUsername/ui/LoginForm/LoginForm.module.scss
  frontend-next-migration/src/features/AuthByUsername/ui/LoginForm/LoginForm.test.tsx
  frontend-next-migration/src/features/AuthByUsername/ui/LoginForm/LoginForm.tsx
  frontend-next-migration/src/features/AuthByUsername/ui/RegisterForm/RegisterForm.async.tsx
  frontend-next-migration/src/features/AuthByUsername/ui/RegisterForm/RegisterForm.module.scss
  frontend-next-migration/src/features/AuthByUsername/ui/RegisterForm/RegisterForm.test.tsx
  frontend-next-migration/src/features/AuthByUsername/ui/RegisterForm/RegisterForm.tsx
  frontend-next-migration/src/preparedPages/AuthPages/index.ts
  frontend-next-migration/src/preparedPages/AuthPages/ui/AuthLayout/AuthLayout.module.scss
  frontend-next-migration/src/preparedPages/AuthPages/ui/AuthLayout/AuthLayout.tsx
  frontend-next-migration/src/preparedPages/AuthPages/ui/AuthLoginPage/AuthLoginPage.async.tsx
  frontend-next-migration/src/preparedPages/AuthPages/ui/AuthLoginPage/AuthLoginPage.tsx
  frontend-next-migration/src/preparedPages/AuthPages/ui/AuthMainPage/AuthMainPage.async.tsx
  frontend-next-migration/src/preparedPages/AuthPages/ui/AuthMainPage/AuthMainPage.tsx
  frontend-next-migration/src/preparedPages/AuthPages/ui/AuthRegisterPage/AuthRegisterPage.async.tsx
  frontend-next-migration/src/preparedPages/AuthPages/ui/AuthRegisterPage/AuthRegisterPage.tsx
  frontend-next-migration/src/preparedPages/AuthPages/ui/AuthSubLoginPage/AuthSubLoginPage.async.tsx
  frontend-next-migration/src/preparedPages/AuthPages/ui/AuthSubLoginPage/AuthSubLoginPage.tsx
  frontend-next-migration/src/preparedPages/AuthPages/ui/AuthSubRegisterPage/AuthSubRegisterPage.async.tsx
  frontend-next-migration/src/preparedPages/AuthPages/ui/AuthSubRegisterPage/AuthSubRegisterPage.tsx
  frontend-next-migration/src/shared/ui/CustomForm/ui/CustomForm.tsx
  frontend-next-migration/src/widgets/AuthWidget/index.ts
  frontend-next-migration/src/widgets/AuthWidget/ui/AuthWidget.tsx
Labels: refactor

#254 add-footer-to-every-page
  frontend-next-migration/src/app/[lng]/(helper)/admin/page.tsx
  frontend-next-migration/src/app/[lng]/(helper)/comics/layout.tsx
  frontend-next-migration/src/app/[lng]/(helper)/coming/layout.tsx
  frontend-next-migration/src/app/[lng]/(helper)/data-policy/layout.tsx
  frontend-next-migration/src/app/[lng]/(helper)/hero-development/layout.tsx
  frontend-next-migration/src/app/[lng]/(helper)/heroes/layout.tsx
  frontend-next-migration/src/app/[lng]/(helper)/layout.tsx
  frontend-next-migration/src/app/[lng]/(helper)/news/layout.tsx
  frontend-next-migration/src/app/[lng]/(helper)/peli/layout.tsx
  frontend-next-migration/src/app/[lng]/(helper)/picture-galleries/layout.tsx
  frontend-next-migration/src/app/[lng]/(helper)/privacy/layout.tsx
  frontend-next-migration/src/app/[lng]/(helper)/profile/layout.tsx
  frontend-next-migration/src/preparedPages/CookiesPage/ui/CookiesPage.tsx
  frontend-next-migration/src/preparedPages/GameArtPage/ui/GameArtPage.tsx
Labels: enhancement, refactor

#255 fix/margin-tops and removed unnecessary classes from clans
  frontend-next-migration/src/preparedPages/ClanPages/ui/ClanMainPage/ClanMainPage.module.scss
  frontend-next-migration/src/preparedPages/MainPage/ui/page.module.scss
  frontend-next-migration/src/preparedPages/MembersPage/ui/MembersPage.module.scss
Labels: refactor

#257 Leo/feature/add layout loader
  frontend-next-migration/src/app/[lng]/(helper)/about/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/admin/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/artGame/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/auth/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/comics/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/coming/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/cookies/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/data-policy/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/hero-development/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/heroes/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/layout.tsx
  frontend-next-migration/src/app/[lng]/(helper)/news/layout.tsx
  frontend-next-migration/src/app/[lng]/(helper)/news/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/peli/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/picture-galleries/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/privacy/loading.tsx
  frontend-next-migration/src/app/[lng]/(helper)/profile/loading.tsx
  frontend-next-migration/src/app/[lng]/(home)/loading.tsx
Labels: enhancement

#262 Sakari/enhancement/220 reworking pin collapse btn icons in svg format
  frontend-next-migration/src/shared/assets/icons/hidden.svg
  frontend-next-migration/src/shared/assets/icons/pinned.svg
  frontend-next-migration/src/shared/assets/icons/unpin.svg
  frontend-next-migration/src/shared/assets/icons/visible.svg
  frontend-next-migration/src/widgets/Navbar/ui/ToggleCollapseButton/ToggleCollapseButton.module.scss
  frontend-next-migration/src/widgets/Navbar/ui/ToggleCollapseButton/ToggleCollapseButton.tsx
  frontend-next-migration/src/widgets/Navbar/ui/ToggleFixButton/ToggleFixButton.module.scss
  frontend-next-migration/src/widgets/Navbar/ui/ToggleFixButton/ToggleFixButton.tsx
Labels: enhancement

#277 sakari/enc/276-enhancement-request-ensure-parentalauth…
  frontend-next-migration/src/entities/Auth/types/authUser.d.ts
  frontend-next-migration/src/features/AuthByUsername/model/useRegisterForm.test.ts
  frontend-next-migration/src/features/AuthByUsername/model/useRegisterForm.ts
Labels: bug, enhancement
